routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\FavouritesController;
use App\Http\Controllers\QuestionAnswerController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/questions/{slug}/download', [QuestionsController::class, 'downloadAsPDF'])->name('questions.download');
Route::resource('/questions', QuestionsController::class)->except('show');

Route::get('/questions/{slug}', [QuestionsController::class, 'show']);

Route::resource('/tags', TagsController::class)->only(['index', 'show']);

Route::put('questions/{question}/answers/{answer}/best-answer', [QuestionAnswerController::class, 'markAsBest'])->name('markAsBest');
Route::put('questions/{question}/answers/{answer}/unmark-best-answer', [QuestionAnswerController::class, 'unMarkAsBest'])->name('unMarkAsBest');

Route::middleware(['auth'])->group(function() {
    Route::get('questions/{question}/answer/create', [QuestionAnswerController::class, 'create'])->name('questionAnswers.create');
    Route::get('question/{question}/answer/{answer}/edit', [QuestionAnswerController::class, 'edit'])->name('questionAnswers.edit');
    Route::put('question/{question}/answer/{answer}/update', [QuestionAnswerController::class, 'update'])->name('questionAnswers.update');
    Route::post('questions/{question}/answer', [QuestionAnswerController::class, 'store'])->name('questionAnswers.store');
});

Route::post('questions/{question}/markAsFavourite', [FavouritesController::class, 'store'])->name('questions.favourite');
Route::delete('questions/{question}/unmarkFavourite', [FavouritesController::class, 'destroy'])->name('questions.unfavourite');

Route::post('questions/{question}/votes/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.vote');
Route::post('answers/{answer}/votes/{vote}', [VotesController::class, 'voteAnswer'])->name('answers.vote');

Route::get('/users/', [UsersController::class, 'index'])->name('users.index');
Route::get('/users/notifications', [UsersController::class, 'notifications'])->name('users.notifications')->middleware(['auth']);
Route::put('/users/notifications/{notification}/markAsRead', [UsersController::class, 'markAsRead'])->name('users.markNotificationAsRead');
Route::put('/users/markAllAsRead', [UsersController::class, 'markAllAsRead'])->name('users.markAllNotificationsAsRead');
Route::get('/users/{user}/profile', [UsersController::class, 'show'])->name('users.profile');
Route::get('/users/{user}/favourites', [UsersController::class, 'viewFavourites'])->name('users.viewFavourites');
Route::get('/users/{user}/edit', [UsersController::class, 'edit'])->name('users.edit');
Route::put('/users/{user}/edit', [UsersController::class, 'update'])->name('users.update');

Route::get('/home-page', [UsersController::class, 'index'])->name('users.homepage');

Route::delete('questions/{question}/answer/{answer}/delete', [QuestionAnswerController::class, 'destroy'])->name('questionAnswers.delete');
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Answer.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Votable;

require_once('traits/Votable.trait.php');

class Answer extends Model
{
    use HasFactory, Votable;

    protected $guarded = [];

    public static function boot() {
        parent::boot();
        static::created(function($answer) {
            $answer->question->increment('answers_count');
        });
    }

    public function getIsModifiedAttribute() {
        return ($this->modified_at);
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    public function getModifiedDateAttribute() {
        $date = new Carbon($this->modified_at);
        return $date->diffForHumans();
    }

    public function getUrlAttribute(){
        return "{$this->question->url}#{$this->question->id}-{$this->id}";
    }

    public function isBest(Question $question){
        return $question->best_answer_id === $this->id;
    }

    public function question() {
        return $this->belongsTo(Question::class);
    }

    public function author() {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function votes() {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }
}

app/Models/Question.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Str;
use Symfony\Component\VarDumper\VarDumper;
use Votable;

require_once('traits/Votable.trait.php');

class Question extends Model
{
    protected $guarded = [];

    use HasFactory, Votable;

    public function markAsBest(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function unMarkAsBest() {
        $this->best_answer_id = null;
        $this->save();
    }

    /**
     * Mutators
     */

    public function setTitleAttribute($title){
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }

    /**
     * Accessor
     */

    public function getUrlAttribute() {
        return "questions/$this->slug";
    }

    public function getIsModifiedAttribute() {
        return ($this->modified_at);
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    public function getModifiedDateAttribute() {
        $date = new Carbon($this->modified_at);
        return $date->diffForHumans();
    }

    public function getStylesForAnswerAttribute(){
        if($this->answers_count > 0){
            if($this->best_answer_id){
                return "has-best-answer";
            }   else    {
                return "answered";
            }
        }
        return "unanswered";
    }

    public function getIsFavouriteAttribute() {
        return $this->favourites()->where(["user_id" => auth()->id()])->count() > 0;
    }

    public function getFavouritesCountAttribute() {
        return $this->favourites->count();
    }

    public function getAnswersWithFavouriteAttribute() {
        $answers = array();
        foreach($this->answers as $answer) {
            if($answer->isBest($this)) {
                array_unshift($answers, $answer);
            }   else{
                array_push($answers, $answer);
            }
        }
        return $answers;
    }

    public function getTagsCountAttribute() {
        return $this->tags()->count();
    }

    public function hasThisTag(Tag $tag) {
        return $this->tags()->where("tag_id", $tag->id)->get()->count() == 1;
    }

    /**
     * Relationship Methods
     */

    public function owner(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function answers() {
        return $this->hasMany(Answer::class);
    }

    public function favourites() {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function votes() {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }

    public function tags() {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'bio',
        'image'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Accessors
     */

    public function getAvatarAttribute(){
        if($this->image !== null) {
            return asset("storage/$this->image");
        }
        $name = $this->name;
        return "https://ui-avatars.com/api/?size=40&rounded=true&name={$name}";
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    /**
     * Relationship Methods
     */

    public function questions(){
        return $this->hasMany(Question::class);
    }

    public function answers() {
        return $this->hasMany(Answer::class);
    }

    public function favourites() {
        return $this->belongsToMany(Question::class)->withTimestamps();
    }

    public function voteQuestions() {
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }

    public function voteAnswers() {
        return $this->morphedByMany(Answer::class, 'votes')->withTimestamps();
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Question;
use App\Models\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function notifications() {
        $notifications = auth()->user()->unreadNotifications()->paginate(25);
        session()->flash('location', 'notifications');
        return view('users.notifications', compact(['notifications']));
    }

    public function markAsRead($notification) {
        $notification = auth()->user()->notifications()->find($notification);
        $notification->markAsRead();
        return redirect()->back();
    }

    public function markAllAsRead() {
        auth()->user()->unreadNotifications->markAsRead();
        return redirect()->back();
    }

    public function index() {
        $users = User::paginate(12);
        session()->flash('location', "users");
        return view('users.index', compact(['users']));
    }

    public function fetchAll() {
        $users = User::all();
        return response(["data" => $users, "code" => 200], 200);
    }

    public function show(User $user){
        session()->flash('location', "users");
        $user = User::with([
            'questions' => function($query) { $query->latest(); },
            'answers' => function($query) { $query->latest(); }
            ])->find($user->id);
        $userQuestions = $user->questions;
        $votes['questions'] = 0;
        $views = 0;
        foreach($userQuestions as $question){
            $votes['questions'] += $question->votes_count;
            $views += $question->views_count;
        }
        $userAnswers = $user->answers;
        $votes['answers'] = 0;
        foreach($userAnswers as $answer){
            $votes['answers'] += $answer->votes_count;
        }
        $usedTags = Question::with("tags")->where("user_id", $user->id)->get()->pluck("tags")->flatten();
        $tags = [];
        foreach($usedTags as $tag) {
            if(isset($tags[$tag->id])) {
                $tags[$tag->id]["count"] += 1;
            } else {
                $tags[$tag->id] = $tag;
                $tags[$tag->id]["count"] = 1;
            }
        }
        return view('users.profile', compact(['user', 'votes', 'views', 'tags']));
    }

    public function edit(User $user) {
        session()->flash('location', "users");
        return view('users.edit', compact(['user']));
    }

    public function update(Request $request, User $user) {
        if($request->file('image')){
            $image = $request->file('image')->store('user-images');
            $user->update([
                'image' => $image
            ]);
        }
        $user->update([
            'bio' => $request->bio,
            'name' => $request->name,
        ]);

        return redirect(route('users.profile', $user));
    }

    public function viewFavourites(User $user) {
        $questions = $user->favourites()->paginate(10);
        return view("users.favourites", compact(['questions', 'user']));
    }
}

resources/views/users/favourites.blade.php
@extends('frontend-layouts.app')


@section('page-level-styles')
    <style>
        .answers {
            padding: 2px;
            border-radius: 5px;
        }

        .answers.answered {
            border: solid 1px #4fc627;
            color: #4fc627;
        }

        .answers.has-best-answer {
            border: solid 1px #4fc627;
            background: #4fc627;
            color: white;
        }

        .answers.unanswered {
            border: solid 1px red;
            color: red;
        }
    </style>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="d-flex flex-column mt-5 list-group list-group-flush">
            <div class="list-group-item bg-transparent">
                <div class="d-flex justify-content-between mb-4">
                    <h3 class="flex-item text-white">Favourite Questions</h3>
                    <div id="action-buttons">
                        <a href="{{ route('users.profile', $user) }}" class="btn btn-dark me-3">Back To Profile</a>
                        <a href="{{ route('questions.create') }}" class="btn btn-dark">Ask a Question!</a>
                    </div>
                </div>
            </div>
            <div id="questionList" class="list-group-item bg-transparent mt-4">
                @foreach ($questions as $question)
                    <div class="row align-items-center mb-2">
                        <div class="col-md-1 text-white-50 views">
                            {{ $question->views_count }} {{ Str::plural('view', $question->views_count) }}
                        </div>
                        <div class="col-md-10">
                            <a href="{{ url($question->url) }}" class="text-primary text-decoration-none fs-5">{{ $question->title }}</a>
                        </div>
                        <div class="d-flex col-md-1 justify-content-end">
                            @can('update', $question)
                                <a href="{{ route('questions.edit', $question) }}" class="btn btn-sm btn-secondary text-warning me-2"><strong>Edit</strong></a>
                            @endcan
                            @can('delete', $question)
                                <form action="{{ route('questions.destroy', $question) }}" class="d-inline" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-secondary" style="color: red"><strong>Delete</strong></button>
                                </form>
                            @endcan
                        </div>
                    </div>
                    <div class="row align-items-center mb-2">
                        <div class="col-md-1 answers {{ $question->styles_for_answer }}">
                            {{ $question->answers_count }} {{ Str::plural('answer', $question->answers_count) }}
                        </div>
                        <div class="col-md-11 fs-6 text-white-50 fw-light">
                                {!! \Illuminate\Support\Str::limit($question->body, 250) !!}
                        </div>
                    </div>
                    <div class="row align-items-center mb-2">
                        <div class="col-md-1 text-white-50 {{ $question->styles_for_answer }}">
                            {{ $question->votes_count }} {{ Str::plural('vote', $question->votes_count) }}
                        </div>
                        <div class="col-md-11">
                            <span class="submitter-details fs-6 text-white-50 me-5">
                                Submitted By:
                                <a href="{{ route('users.profile', $question->owner) }}" class="text-primary text-decoration-none fs-6 fw-light ms-2">
                                    <img src="{{ $question->owner->avatar}}" height="25px">
                                    {{ $question->owner->name }}
                                </a>
                            </span>
                            <span class="submission-details fs-6 text-white-50">
                                @if($question->is_modified)
                                    Modified: <p class="fw-light d-inline">{{ $question->modified_date }}.</p>
                                @else
                                    Submitted: <p class="fw-light d-inline">{{ $question->created_date }}.</p>
                                @endif
                            </span>
                        </div>
                    </div>
                    <hr class="text-white">
                @endforeach
            </div>
            <div class="questionListFooter list-group-item bg-transparent mt-2 mb-5">
                {{ $questions->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('frontend-layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="d-flex flex-column mt-5 list-group list-group-flush">
            <div class="list-group-item bg-transparent">
                <div class="d-flex justify-content-between mb-4">
                    <h3 class="flex-item text-white">Users</h3>
                    <a href="{{ route('questions.index') }}" class="btn btn-dark">Back To Questions</a>
                </div>
            </div>
            <div class="list-group-item bg-transparent d-flex flex-wrap">
                @foreach ($users as $user)
                    <div class="col-md-4 p-3">
                        <div class="tagHeader row d-flex align-items-center mb-2">
                            <div class="col-md-2">
                                <img src="{{ $user->avatar }}">
                            </div>
                            <div class="col-md-5 text-primary">
                                <a href="{{ route('users.profile', $user) }}" class="fs-6 text-decoration-none">{{ $user->name }}</a>
                            </div>
                            <div class="col-md-5">
                                <p class="text-white fs-6 m-0">
                                    Questions Asked: {{ $user->questions->count() }}
                                </p>
                                <p class="text-white fs-6 m-0">
                                    Answers Given: {{ $user->answers->count()}}
                                </p>
                            </div>
                        </div>
                        @if($user->bio !== null)
                            <div class="userBio row">
                                <div class="col-md-12">
                                    <div class="mt-2 mb-2 fs-6 p-2 bg-dark rounded-1 text-white-50">
                                        {!! $user->bio !!}
                                    </div>
                                </div>
                            </div>
                        @endif
                    </div>
                @endforeach
            </div>
            <div class="questionListFooter list-group-item bg-transparent mt-2 mb-5">
                {{ $users->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/users/profile.blade.php
@extends('frontend-layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="d-flex flex-column mt-5 list-group list-group-flush">
            <div class="list-group-item bg-transparent">
                <div id="profileTitle" class="d-flex justify-content-between text-white">
                    <h3 class="flex-item text-white m-0"><img src="{{ $user->avatar }}" class="rounded-circle" width="40px"> {{ $user->name }}</h3>
                    <div id="user-actions">
                        @can('viewFavourites', $user)
                            <a href="{{ route('users.viewFavourites', $user) }}" class="btn btn-dark text-success align-self-center fw-bold">View Favourites</a>
                        @endcan
                        @can('update', $user)
                            <a href="{{ route('users.edit', $user) }}" class="btn btn-dark text-warning align-self-center fw-bold">Edit Profile</a>
                        @endcan
                    </div>
                </div>
                <div id="profileHeader" class="d-flex justify-content-start mb-4 text-white-50 ms-5">
                    <small id="joinDate">
                        Joined: {{ $user->created_date }}
                    </small>
                    <small id="lastActive" class="ms-5">
                        Last Active: 10 minutes ago
                    </small>
                </div>
            </div>
            <div class="list-group-item bg-transparent text-white mt-5">
                <div class="row">
                    <div class="col-md-4">
                        <div id="statistics">
                            <h4 class="ms-4">
                                Stats
                            </h4>
                            <div class="bg-dark ms-4 mt-3 me-4 p-3 rounded-2">
                                <div class="row">
                                    <div class="col-md-6">
                                        Questions Asked: {{ $user->questions->count() }}
                                    </div>
                                    <div class="col-md-6">
                                        Answers Given: {{ $user->answers->count() }}
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class="col-md-6">
                                        Question Votes: {{ $votes['questions'] }}
                                    </div>
                                    <div class="col-md-6">
                                        Answer Votes: {{ $votes['answers'] }}
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class="col-md-6">
                                        Views: {{ $views }}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="tag-details" class="mt-4">
                            <h4 class="ms-4">
                                Tags Used
                            </h4>
                            <div class="bg-dark ms-4 mt-3 me-4 p-3 rounded-2">
                                @foreach ($tags as $tag)
                                    <div class="row mt-1">
                                        <div class=" tag-name col-6">
                                            <a href="{{ route('tags.show', $tag->id)}}" class="text-decoration-none fw-bold text-light">{{ $tag->name }}</a>
                                        </div>
                                        <div class="tag-count col-6">{{ $tag->count }}</div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div id="userAbout">
                            <h4>About</h4>
                            @if($user->bio !== null)
                                <div class="bg-dark mt-3 rounded-2 p-3">
                                    {!! $user->bio !!}
                                </div>
                            @endif
                        </div>
                        <div id="userPosts" class="{{$user->bio !== "" ? "mt-5" : "mt-3"}}">
                            <ul class="nav nav-tabs border-0" id="postsTabs" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active text-decoration-none border-0 fw-bold fs-5" id="questions-tab" data-bs-toggle="tab" data-bs-target="#questions-tab-pane" type="button" role="tab" aria-controls="questions-tab-pane" aria-selected="true"
                                    style="
                                        --bs-nav-link-color: #f8f9fa; --bs-nav-tabs-link-active-color: #f8f9fa;
                                        --bs-nav-tabs-link-active-bg: #212529;
                                        --bs-nav-tabs-link-hover-border-color: #6c757d; --bs-nav-tabs-link-active-border-color: #212529;
                                    ">
                                        Questions
                                    </button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link text-decoration-none border-0 fw-bold fs-5" id="answers-tab" data-bs-toggle="tab" data-bs-target="#answers-tab-pane" type="button" role="tab" aria-controls="answers-tab-pane" aria-selected="false"
                                    style="
                                        --bs-nav-link-color: #f8f9fa; --bs-nav-tabs-link-active-color: #f8f9fa;
                                        --bs-nav-tabs-link-active-bg: #212529;
                                        --bs-nav-tabs-link-active-border-color: #212529;
                                    ">
                                        Answers
                                    </button>
                                </li>
                            </ul>
                            <div class="tab-content p-3 bg-dark" id="myTabContent">
                                <div class="tab-pane fade show active" id="questions-tab-pane" role="tabpanel" aria-labelledby="questions-tab" tabindex="0">
                                    @foreach ($user->questions as $question)
                                        <div class="row align-items-center mb-2">
                                                <a href="{{ url($question->url) }}" class="text-primary text-decoration-none fs-5">{{ $question->title }}</a>
                                        </div>
                                        <div class="row align-items-center mb-2">
                                            <div class="col-md-11 fs-6 text-white-50 fw-light">
                                                    {!! \Illuminate\Support\Str::limit($question->body, 125) !!}
                                            </div>
                                        </div>
                                        <hr class="text-white">
                                    @endforeach
                                </div>
                                <div class="tab-pane fade" id="answers-tab-pane" role="tabpanel" aria-labelledby="answers-tab" tabindex="0">
                                    @foreach ($user->answers as $answer)
                                        <div class="row align-items-center mb-2">
                                            <div class="col-md-10">
                                                <a href="{{ url($answer->url) }}" class="text-primary text-decoration-none fs-5">{{ $answer->question->title }}</a>
                                            </div>
                                        </div>
                                        <div class="row align-items-center mb-2">
                                            <div class="col-md-11 fs-6 text-white-50 fw-light">
                                                    {!! \Illuminate\Support\Str::limit($answer->body, 125) !!}
                                            </div>
                                        </div>
                                        <hr class="text-white">
                                    @endforeach
                                </div>
                              </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection