routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\FavouritesController;
use App\Http\Controllers\QuestionAnswerController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/questions/{slug}/download', [QuestionsController::class, 'downloadAsPDF'])->name('questions.download');
Route::resource('/questions', QuestionsController::class)->except('show');

Route::get('/questions/{slug}', [QuestionsController::class, 'show']);

Route::resource('/tags', TagsController::class)->only(['index', 'show']);

Route::put('questions/{question}/answers/{answer}/best-answer', [QuestionAnswerController::class, 'markAsBest'])->name('markAsBest');
Route::put('questions/{question}/answers/{answer}/unmark-best-answer', [QuestionAnswerController::class, 'unMarkAsBest'])->name('unMarkAsBest');

Route::middleware(['auth'])->group(function() {
    Route::get('questions/{question}/answer/create', [QuestionAnswerController::class, 'create'])->name('questionAnswers.create');
    Route::get('question/{question}/answer/{answer}/edit', [QuestionAnswerController::class, 'edit'])->name('questionAnswers.edit');
    Route::put('question/{question}/answer/{answer}/update', [QuestionAnswerController::class, 'update'])->name('questionAnswers.update');
    Route::post('questions/{question}/answer', [QuestionAnswerController::class, 'store'])->name('questionAnswers.store');
});

Route::post('questions/{question}/markAsFavourite', [FavouritesController::class, 'store'])->name('questions.favourite');
Route::delete('questions/{question}/unmarkFavourite', [FavouritesController::class, 'destroy'])->name('questions.unfavourite');

Route::post('questions/{question}/votes/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.vote');
Route::post('answers/{answer}/votes/{vote}', [VotesController::class, 'voteAnswer'])->name('answers.vote');

Route::get('/users/', [UsersController::class, 'index'])->name('users.index');
Route::get('/users/notifications', [UsersController::class, 'notifications'])->name('users.notifications')->middleware(['auth']);
Route::put('/users/notifications/{notification}/markAsRead', [UsersController::class, 'markAsRead'])->name('users.markNotificationAsRead');
Route::put('/users/markAllAsRead', [UsersController::class, 'markAllAsRead'])->name('users.markAllNotificationsAsRead');
Route::get('/users/{user}/profile', [UsersController::class, 'show'])->name('users.profile');
Route::get('/users/{user}/favourites', [UsersController::class, 'viewFavourites'])->name('users.viewFavourites');
Route::get('/users/{user}/edit', [UsersController::class, 'edit'])->name('users.edit');
Route::put('/users/{user}/edit', [UsersController::class, 'update'])->name('users.update');

Route::get('/home-page', [UsersController::class, 'index'])->name('users.homepage');

Route::delete('questions/{question}/answer/{answer}/delete', [QuestionAnswerController::class, 'destroy'])->name('questionAnswers.delete');
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Answer.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Votable;

require_once('traits/Votable.trait.php');

class Answer extends Model
{
    use HasFactory, Votable;

    protected $guarded = [];

    public static function boot() {
        parent::boot();
        static::created(function($answer) {
            $answer->question->increment('answers_count');
        });
    }

    public function getIsModifiedAttribute() {
        return ($this->modified_at);
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    public function getModifiedDateAttribute() {
        $date = new Carbon($this->modified_at);
        return $date->diffForHumans();
    }

    public function getUrlAttribute(){
        return "{$this->question->url}#{$this->question->id}-{$this->id}";
    }

    public function isBest(Question $question){
        return $question->best_answer_id === $this->id;
    }

    public function question() {
        return $this->belongsTo(Question::class);
    }

    public function author() {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function votes() {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }
}

app/Models/Question.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Str;
use Symfony\Component\VarDumper\VarDumper;
use Votable;

require_once('traits/Votable.trait.php');

class Question extends Model
{
    protected $guarded = [];

    use HasFactory, Votable;

    public function markAsBest(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function unMarkAsBest() {
        $this->best_answer_id = null;
        $this->save();
    }

    /**
     * Mutators
     */

    public function setTitleAttribute($title){
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }

    /**
     * Accessor
     */

    public function getUrlAttribute() {
        return "questions/$this->slug";
    }

    public function getIsModifiedAttribute() {
        return ($this->modified_at);
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    public function getModifiedDateAttribute() {
        $date = new Carbon($this->modified_at);
        return $date->diffForHumans();
    }

    public function getStylesForAnswerAttribute(){
        if($this->answers_count > 0){
            if($this->best_answer_id){
                return "has-best-answer";
            }   else    {
                return "answered";
            }
        }
        return "unanswered";
    }

    public function getIsFavouriteAttribute() {
        return $this->favourites()->where(["user_id" => auth()->id()])->count() > 0;
    }

    public function getFavouritesCountAttribute() {
        return $this->favourites->count();
    }

    public function getAnswersWithFavouriteAttribute() {
        $answers = array();
        foreach($this->answers as $answer) {
            if($answer->isBest($this)) {
                array_unshift($answers, $answer);
            }   else{
                array_push($answers, $answer);
            }
        }
        return $answers;
    }

    public function getTagsCountAttribute() {
        return $this->tags()->count();
    }

    public function hasThisTag(Tag $tag) {
        return $this->tags()->where("tag_id", $tag->id)->get()->count() == 1;
    }

    /**
     * Relationship Methods
     */

    public function owner(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function answers() {
        return $this->hasMany(Answer::class);
    }

    public function favourites() {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function votes() {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }

    public function tags() {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'bio',
        'image'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Accessors
     */

    public function getAvatarAttribute(){
        if($this->image !== null) {
            return asset("storage/$this->image");
        }
        $name = $this->name;
        return "https://ui-avatars.com/api/?size=40&rounded=true&name={$name}";
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    /**
     * Relationship Methods
     */

    public function questions(){
        return $this->hasMany(Question::class);
    }

    public function answers() {
        return $this->hasMany(Answer::class);
    }

    public function favourites() {
        return $this->belongsToMany(Question::class)->withTimestamps();
    }

    public function voteQuestions() {
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }

    public function voteAnswers() {
        return $this->morphedByMany(Answer::class, 'votes')->withTimestamps();
    }
}

resources/views/answers/create.blade.php
@extends('frontend-layouts.app')

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css" />
    <link rel="stylesheet" href="{{ asset('ckeditor4/content.css') }}">
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="d-flex flex-column mt-5 list-group list-group-flush">
                <div class="list-group-item bg-transparent">
                    <div class="d-flex justify-content-between mb-4">
                        <h3 class="flex-item text-white">Answer the Question</h3>
                        <a href="{{ url($question->url) }}" class="btn btn-dark">Back to Question</a>
                    </div>
                </div>

                <div class="list-group-item rounded-1 bg-light" style="--bs-bg-opacity: 0.23">
                    <form action="{{ route('questionAnswers.store', $question) }}" method="POST" class="mt-2">
                        @csrf
                        <div class="form-group mb-3">
                            <label for="body" class="text-white fs-5">Answer</label>
                            {{-- <input type="hidden" class="form-control" value="{{ old('body') }}" name="body" id="body"/>
                            <trix-editor input="body" placeholder="Answer The Question" class="form-control"></trix-editor> --}}

                            <textarea name="body" id="body"></textarea>

                            @error('body')
                                    <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group mt-3">
                            <input type="submit" value="Submit Answer" class="btn btn-dark">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
    <script src="{{ asset('ckeditor4/ckeditor.js') }}"></script>
    <script src="{{ asset('js/ckeditorMentions.js') }}"></script>
@endsection

resources/views/answers/edit.blade.php
@extends('frontend-layouts.app')

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css" />
    <link rel="stylesheet" href="{{ asset('ckeditor4/content.css') }}">
@endsection

@section('content')
<div class="container">
    <div class="col-md-12">
        <div class="row justify-content-center">
            <div class="d-flex flex-column mt-5 list-group list-group-flush">
                <div class="list-group-item bg-transparent">
                    <div class="d-flex justify-content-between mb-4">
                        <h3 class="flex-item text-white">Edit your Answer</h3>
                        <a href="{{ url($answer->url) }}" class="btn btn-dark">Back to Answer</a>
                    </div>
                </div>

                <div class="list-group-item rounded-1 bg-light" style="--bs-bg-opacity: 0.23">
                    <form action="{{ route('questionAnswers.update', [$question, $answer]) }}" method="POST" class="mt-2">
                        @csrf
                        @method("PUT")
                        <div class="form-group mb-3">
                            <label for="body" class="text-white fs-5">Answer</label>
                            {{-- <input type="hidden" class="form-control" value="{{ old('body', $answer->body) }}" name="body" id="body"/>
                            <trix-editor input="body" placeholder="Answer The Question" class="form-control"></trix-editor> --}}

                            <textarea name="body" id="body">{{ old('body', $answer->body) }}</textarea>

                            @error('body')
                                    <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group mt-3">
                            <input type="submit" value="Submit Answer" class="btn btn-dark">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
    <script src="{{ asset('ckeditor4/ckeditor.js') }}"></script>
    <script src="{{ asset('js/ckeditorMentions.js') }}"></script>
@endsection

resources/views/answers/index.blade.php
<div class="row mt-5">
    <div class="col-md-12">
        <div class="d-flex flex-column list-group list-group-flush">
            <div class="list-group-item bg-transparent">
                <div class="d-flex justify-content-between mb-4">
                    <h3 class="flex-item text-white">{{ $question->answers_count }} {{ Str::plural('Answer', $question->answers_count) }}</h3>
                </div>
            </div>
        </div>
        <div id="answerList" class="list-group-item bg-transparent mt-4">
            @foreach ($question->answers_with_favourite as $answer)
                <div id="{{ "$question->id-$answer->id" }}" class="row align-items-center mb-2">
                    <div class="d-flex flex-column align-items-center col-md-1">
                        @auth
                            <div class="mb-3">
                                <form action="{{ route('answers.vote', [$answer, 1]) }}" method="POST">
                                    @csrf
                                    <button type="submit" width="100%" title="Vote Up" class="vote-up border-0 bg-transparent {{ $answer->hasMarkedUpvote(auth()->user()) ? "text-success" : "text-white" }}">
                                        <i class="fa-solid fa-caret-up fa-3x"></i>
                                    </button>
                                </form>
                                <h4 class="m-0 text-muted text-center">{{ $answer->votes_count }}</h4>
                                <form action="{{ route('answers.vote', [$answer, -1]) }}" method="POST">
                                    @csrf
                                    <button type="submit" title="Vote Down" class="vote-down border-0 bg-transparent {{ $answer->hasMarkedDownvote(auth()->user()) ? "text-danger" : "text-white" }}">
                                        <i class="fa fa-caret-down fa-3x"></i>
                                    </button>
                                </form>
                            </div>
                        @else
                            <div class="mb-2">
                                <form action="{{ route('login') }}" method="GET">
                                    @csrf
                                    <button type="submit" title="Vote Up" class="vote-up text-center border-0 bg-transparent text-white">
                                        <i class="fa fa-caret-up fa-3x"></i>
                                    </button>
                                </form>
                                <h4 class="m-0 text-muted text-center">{{ $answer->votes_count }}</h4>
                                <form action="{{ route('login') }}" method="GET">
                                    @csrf
                                    <button type="submit" title="Vote Down" class="vote-down text-center border-0 bg-transparent text-white">
                                        <i class="fa fa-caret-down fa-3x"></i>
                                    </button>
                                </form>
                            </div>
                        @endauth
                        <div class="mt-3">
                            @can('markAsBest', $answer)
                                <form action="{{route($question->best_answer_id == $answer->id ? 'unMarkAsBest':'markAsBest', ['question' => $question, 'answer'=>$answer])}}" method="POST">
                                    @csrf
                                    @method('PUT')
                                    <button title="Mark as Best"
                                            class="favorite d-block text-center mb-2 border-0 bg-transparent"
                                            type="submit">
                                        <i class="fa fa-check fa-2x p-2 {{ $answer->isBest($question) ? 'text-dark bg-success rounded-2' : 'text-white' }}"></i>
                                    </button>
                                </form>
                            @else
                                @if($answer->isBest($question))
                                    <i class="fa fa-check fa-2x text-dark bg-success rounded-2 p-2"></i>
                                @endif
                            @endcan
                        </div>
                    </div>
                    <div class="col-md-10 text-white align-self-start mt-2">
                        <div class="answer-body mb-5">
                            {!! $answer->body !!}
                        </div>
                        <div class="submitter-details fs-6 text-white-50 me-5">
                            Answered By:
                            <a href="{{ route('users.profile', $answer->author) }}" class="text-primary text-decoration-none fs-6 fw-light ms-2">
                                <img src="{{ $answer->author->avatar}}" height="25px" class="rounded-circle">
                                {{ $answer->author->name }}
                            </a>
                        </div>
                        <div class="submission-details fs-6 text-white-50">
                            @if($answer->is_modified)
                                Modified: <p class="fw-light d-inline">{{ $answer->modified_date }}.</p>
                            @else
                                Answered: <p class="fw-light d-inline">{{ $answer->created_date }}.</p>
                            @endif
                        </div>
                    </div>
                    <div class="d-flex col-md-1 justify-content-end align-self-end">
                        @can('update', $answer)
                            <a href="{{ route('questionAnswers.edit', [$question, $answer]) }}" class="btn btn-sm btn-secondary text-warning me-2"><strong>Edit</strong></a>
                        @endcan
                        @can('delete', [$answer, $question])
                            <form action="{{ route('questionAnswers.delete', [$question, $answer]) }}" class="d-inline" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-secondary" style="color: red"><strong>Delete</strong></button>
                            </form>
                        @endcan
                    </div>
                    </div>
                    <hr class="text-white-50 mt-4">
                @endforeach
            </div>
        </div>
    </div>
</div>