routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\FavouritesController;
use App\Http\Controllers\QuestionAnswerController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/questions/{slug}/download', [QuestionsController::class, 'downloadAsPDF'])->name('questions.download');
Route::resource('/questions', QuestionsController::class)->except('show');

Route::get('/questions/{slug}', [QuestionsController::class, 'show']);

Route::resource('/tags', TagsController::class)->only(['index', 'show']);

Route::put('questions/{question}/answers/{answer}/best-answer', [QuestionAnswerController::class, 'markAsBest'])->name('markAsBest');
Route::put('questions/{question}/answers/{answer}/unmark-best-answer', [QuestionAnswerController::class, 'unMarkAsBest'])->name('unMarkAsBest');

Route::middleware(['auth'])->group(function() {
    Route::get('questions/{question}/answer/create', [QuestionAnswerController::class, 'create'])->name('questionAnswers.create');
    Route::get('question/{question}/answer/{answer}/edit', [QuestionAnswerController::class, 'edit'])->name('questionAnswers.edit');
    Route::put('question/{question}/answer/{answer}/update', [QuestionAnswerController::class, 'update'])->name('questionAnswers.update');
    Route::post('questions/{question}/answer', [QuestionAnswerController::class, 'store'])->name('questionAnswers.store');
});

Route::post('questions/{question}/markAsFavourite', [FavouritesController::class, 'store'])->name('questions.favourite');
Route::delete('questions/{question}/unmarkFavourite', [FavouritesController::class, 'destroy'])->name('questions.unfavourite');

Route::post('questions/{question}/votes/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.vote');
Route::post('answers/{answer}/votes/{vote}', [VotesController::class, 'voteAnswer'])->name('answers.vote');

Route::get('/users/', [UsersController::class, 'index'])->name('users.index');
Route::get('/users/notifications', [UsersController::class, 'notifications'])->name('users.notifications')->middleware(['auth']);
Route::put('/users/notifications/{notification}/markAsRead', [UsersController::class, 'markAsRead'])->name('users.markNotificationAsRead');
Route::put('/users/markAllAsRead', [UsersController::class, 'markAllAsRead'])->name('users.markAllNotificationsAsRead');
Route::get('/users/{user}/profile', [UsersController::class, 'show'])->name('users.profile');
Route::get('/users/{user}/favourites', [UsersController::class, 'viewFavourites'])->name('users.viewFavourites');
Route::get('/users/{user}/edit', [UsersController::class, 'edit'])->name('users.edit');
Route::put('/users/{user}/edit', [UsersController::class, 'update'])->name('users.update');

Route::get('/home-page', [UsersController::class, 'index'])->name('users.homepage');

Route::delete('questions/{question}/answer/{answer}/delete', [QuestionAnswerController::class, 'destroy'])->name('questionAnswers.delete');
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'bio',
        'image'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Accessors
     */

    public function getAvatarAttribute(){
        if($this->image !== null) {
            return asset("storage/$this->image");
        }
        $name = $this->name;
        return "https://ui-avatars.com/api/?size=40&rounded=true&name={$name}";
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    /**
     * Relationship Methods
     */

    public function questions(){
        return $this->hasMany(Question::class);
    }

    public function answers() {
        return $this->hasMany(Answer::class);
    }

    public function favourites() {
        return $this->belongsToMany(Question::class)->withTimestamps();
    }

    public function voteQuestions() {
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }

    public function voteAnswers() {
        return $this->morphedByMany(Answer::class, 'votes')->withTimestamps();
    }
}

resources/views/frontend-layouts/partials/message.blade.php
@if(session('success'))
    <div class="alert alert-dismissible alert-success">
        <p><strong>{{ session('success') }}</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@elseif(session('error'))
    <div class="alert alert-dismissible alert-danger">
        <p><strong>Error: {{ session('error') }}</strong></p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif

resources/views/frontend-layouts/partials/navbar.blade.php
<nav class="navbar navbar-expand-lg bg-dark sticky-md-top" z-index="2000" style="height: 7.5%">
    <div class="container">
        <a href="{{ route('questions.index') }}" class="navbar-brand text-light">Stack Overflow</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            </ul>
        </div>
        @auth
            <div class="p-2 nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{{ auth()->user()->avatar }}" class="rounded-circle" width="40px">
                </a>
                <ul class="dropdown-menu justify-content-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ route('users.notifications') }}">Notifications</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{{ route('users.profile', auth()->user())}}">Profile</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{{ route('questions.create') }}">Ask A Question</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li>
                        <form action="{{ route('logout')}}" method="POST">
                            @csrf
                            <button type="submit" class="bg-transparent border-0 ms-3">Log Out</button>
                        </form>
                    </li>
                </ul>
            </div>
        @else
        <div class="p-2 nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Login Options
            </a>
            <ul class="dropdown-menu justify-content-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{{ route('login') }}">Log In</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{{ route('register')}} ">Sign Up</a></li>
            </ul>
        </div>
        @endauth
    </div>
</nav>

resources/views/frontend-layouts/partials/scripts.blade.php
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

resources/views/frontend-layouts/partials/sidebar.blade.php
<ul class="list-group list-group-flush mt-5 text-end">
    <li class="list-group-item  {{ session('location') == "home" ? "bg-secondary" : "bg-transparent" }}">
        <strong>
            <a href="{{ route('users.homepage') }}" class="text-decoration-none {{ session('location') == "home" ? "text-dark" : "text-white-50" }}">
                Home
            </a>
        </strong>
    </li>
    <li class="list-group-item {{ session('location') == "questions" ? "bg-secondary" : "bg-transparent" }}">
        <strong>
            <a href="{{ route('questions.index') }}" class="text-decoration-none {{ session('location') == "questions" ? "text-dark" : "text-white-50" }}">
                Questions
            </a>
        </strong>
    </li>
    <li class="list-group-item {{ session('location') == "tags" ? "bg-secondary" : "bg-transparent" }}">
        <strong>
            <a href="{{ route('tags.index') }}" class="text-decoration-none {{ session('location') == "tags" ? "text-dark" : "text-white-50" }}">
                Tags
            </a>
        </strong>
    </li>
    <li class="list-group-item {{ session('location') == "users" ? "bg-secondary" : "bg-transparent" }}">
        <strong>
            <a href="{{ route('users.index') }}" class="text-decoration-none {{ session('location') == "users" ? "text-dark" : "text-white-50" }}">
                Users
            </a>
        </strong>
    </li>
    <li class="list-group-item {{ session('location') == "ask_question" ? "bg-secondary" : "bg-transparent" }}">
        <strong>
            <a href="{{ route('questions.create') }}" class="text-decoration-none {{ session('location') == "ask_question" ? "text-dark" : "text-white-50" }}">
                Ask A Question
            </a>
        </strong>
    </li>
    <li class="list-group-item {{ session('location') == "notifications" ? "bg-secondary" : "bg-transparent" }}">
        <strong>
            <a href="{{ route('users.notifications') }}" class="text-decoration-none {{ session('location') == "notifications" ? "text-dark" : "text-white-50" }}">
                Notifications
            </a>
        </strong>
    </li>
</ul>

resources/views/frontend-layouts/partials/styles.blade.php
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />