routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\FavouritesController;
use App\Http\Controllers\QuestionAnswerController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/questions/{slug}/download', [QuestionsController::class, 'downloadAsPDF'])->name('questions.download');
Route::resource('/questions', QuestionsController::class)->except('show');

Route::get('/questions/{slug}', [QuestionsController::class, 'show']);

Route::resource('/tags', TagsController::class)->only(['index', 'show']);

Route::put('questions/{question}/answers/{answer}/best-answer', [QuestionAnswerController::class, 'markAsBest'])->name('markAsBest');
Route::put('questions/{question}/answers/{answer}/unmark-best-answer', [QuestionAnswerController::class, 'unMarkAsBest'])->name('unMarkAsBest');

Route::middleware(['auth'])->group(function() {
    Route::get('questions/{question}/answer/create', [QuestionAnswerController::class, 'create'])->name('questionAnswers.create');
    Route::get('question/{question}/answer/{answer}/edit', [QuestionAnswerController::class, 'edit'])->name('questionAnswers.edit');
    Route::put('question/{question}/answer/{answer}/update', [QuestionAnswerController::class, 'update'])->name('questionAnswers.update');
    Route::post('questions/{question}/answer', [QuestionAnswerController::class, 'store'])->name('questionAnswers.store');
});

Route::post('questions/{question}/markAsFavourite', [FavouritesController::class, 'store'])->name('questions.favourite');
Route::delete('questions/{question}/unmarkFavourite', [FavouritesController::class, 'destroy'])->name('questions.unfavourite');

Route::post('questions/{question}/votes/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.vote');
Route::post('answers/{answer}/votes/{vote}', [VotesController::class, 'voteAnswer'])->name('answers.vote');

Route::get('/users/', [UsersController::class, 'index'])->name('users.index');
Route::get('/users/notifications', [UsersController::class, 'notifications'])->name('users.notifications')->middleware(['auth']);
Route::put('/users/notifications/{notification}/markAsRead', [UsersController::class, 'markAsRead'])->name('users.markNotificationAsRead');
Route::put('/users/markAllAsRead', [UsersController::class, 'markAllAsRead'])->name('users.markAllNotificationsAsRead');
Route::get('/users/{user}/profile', [UsersController::class, 'show'])->name('users.profile');
Route::get('/users/{user}/favourites', [UsersController::class, 'viewFavourites'])->name('users.viewFavourites');
Route::get('/users/{user}/edit', [UsersController::class, 'edit'])->name('users.edit');
Route::put('/users/{user}/edit', [UsersController::class, 'update'])->name('users.update');

Route::get('/home-page', [UsersController::class, 'index'])->name('users.homepage');

Route::delete('questions/{question}/answer/{answer}/delete', [QuestionAnswerController::class, 'destroy'])->name('questionAnswers.delete');
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Question.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Str;
use Symfony\Component\VarDumper\VarDumper;
use Votable;

require_once('traits/Votable.trait.php');

class Question extends Model
{
    protected $guarded = [];

    use HasFactory, Votable;

    public function markAsBest(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function unMarkAsBest() {
        $this->best_answer_id = null;
        $this->save();
    }

    /**
     * Mutators
     */

    public function setTitleAttribute($title){
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }

    /**
     * Accessor
     */

    public function getUrlAttribute() {
        return "questions/$this->slug";
    }

    public function getIsModifiedAttribute() {
        return ($this->modified_at);
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    public function getModifiedDateAttribute() {
        $date = new Carbon($this->modified_at);
        return $date->diffForHumans();
    }

    public function getStylesForAnswerAttribute(){
        if($this->answers_count > 0){
            if($this->best_answer_id){
                return "has-best-answer";
            }   else    {
                return "answered";
            }
        }
        return "unanswered";
    }

    public function getIsFavouriteAttribute() {
        return $this->favourites()->where(["user_id" => auth()->id()])->count() > 0;
    }

    public function getFavouritesCountAttribute() {
        return $this->favourites->count();
    }

    public function getAnswersWithFavouriteAttribute() {
        $answers = array();
        foreach($this->answers as $answer) {
            if($answer->isBest($this)) {
                array_unshift($answers, $answer);
            }   else{
                array_push($answers, $answer);
            }
        }
        return $answers;
    }

    public function getTagsCountAttribute() {
        return $this->tags()->count();
    }

    public function hasThisTag(Tag $tag) {
        return $this->tags()->where("tag_id", $tag->id)->get()->count() == 1;
    }

    /**
     * Relationship Methods
     */

    public function owner(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function answers() {
        return $this->hasMany(Answer::class);
    }

    public function favourites() {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    public function votes() {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }

    public function tags() {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Questions\CreateQuestionRequest;
use App\Http\Requests\Questions\UpdateQuestionRequest;
use App\Models\Question;
use App\Models\Tag;
use Barryvdh\DomPDF\Facade\Pdf;
use Carbon\Carbon;

class QuestionsController extends Controller
{
    function __construct() {
        $this->middleware(['auth'])->except(["index", "show"]);
    }

    public function index()
    {
        $questions = Question::with('owner')->latest()->paginate(10);
        session()->flash('location', "questions");
        return view('questions.index', compact(['questions']));
    }

    public function create()
    {
        session()->flash('location', 'ask_question');
        $tags = Tag::all();
        return view('questions.create', compact(['tags']));
    }

    public function store(CreateQuestionRequest $request)
    {
        $question = auth()->user()->questions()->create([
            'title' => $request->title,
            'body' => $request->body
        ]);

        $question->tags()->attach($request->tags);

        session()->flash('success', "Question has been reported to all expert users!");
        return redirect(route('questions.index'));
    }

    public function show(Question $question)
    {
        if(! isset($_COOKIE["$question->slug"])){
            setcookie($question->slug, true);
            $question->increment('views_count');
        }
        session()->flash('location', "questions");
        return view('questions.show', compact(['question']));
    }

    public function downloadAsPDF(Question $question) {
        set_time_limit(300);
        $pdf = Pdf::loadView('questions.show', compact(['question']));
        return $pdf->download("$question->slug.pdf");
    }

    public function edit(Question $question)
    {
        if($this->authorize('update', $question)){
            $tags = Tag::all();
            return view('questions.edit', compact(['question', 'tags']));
        }
        return abort(403);
    }

    public function update(UpdateQuestionRequest $request, Question $question)
    {
        if($this->authorize('update', $question)){
            $question->update([
                'title' => $request->title,
                'body' => $request->body,
                'modified_at' => Carbon::now()
            ]);

            $question->tags()->sync($request->tags);

            session()->flash('success', "Question has been updated and will be answered accordingly soon!");
            return redirect(route('questions.index'));
        }
        return abort(403);
    }

    public function destroy(Question $question)
    {
        if($this->authorize('delete', $question)) {
            $question->delete();
            session()->flash('success', "Question has been deleted!");
            return redirect(route('questions.index'));
        }
        return abort(403);
    }
}

resources/views/questions/create.blade.php
@extends('frontend-layouts.app')

@section('page-level-styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css" />
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="d-flex flex-column mt-5 list-group list-group-flush">
                <div class="list-group-item bg-transparent">
                    <div class="d-flex justify-content-between mb-4">
                        <h3 class="flex-item text-white">Ask a Question</h3>
                        <a href="{{ route('questions.index') }}" class="btn btn-dark">Back to Home</a>
                    </div>
                </div>
                <div class="list-group-item rounded-1 bg-light" style="--bs-bg-opacity: 0.23">
                    <form action="{{ route('questions.store') }}" method="POST" class="mt-2">
                        @csrf
                        <div class="form-group mb-3">
                            <label for="title" class="text-white fs-5">Title</label>
                            <input type="text" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" value="{{ old('title') }}" placeholder="Enter Question Title" name="title" id="title"/>

                            @error('title')
                                    <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group mb-3">
                            <label for="body" class="text-white fs-5">Question</label>
                            <input type="hidden" class="form-control" value="{{ old('body') }}" name="body" id="body"/>
                            <trix-editor input="body" placeholder="Ask Your Question" class="form-control"></trix-editor>

                            @error('body')
                                    <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="form-group mb-3 d-flex flex-column">
                            <label for="tags" class="text-white fs-5">Select Relevant Tags</label>
                            <select name="tags[]" id="tags" class="form-control select2" multiple>
                                @foreach ($tags as $tag)
                                    <option value="{{$tag->id}}">{{$tag->name}}</option>
                                @endforeach
                            </select>

                            @error('tags[]')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>


                        <div class="form-group mb-3">
                            <input type="submit" value="Ask Experts" class="btn btn-dark">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-level-scripts')
<script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        console.log("running");
        $('.select2').select2({
            placeholder: 'Select an option',
            allowClear: true
        });

        </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
@endsection

resources/views/questions/edit.blade.php
@extends('frontend-layouts.app')

@section('page-level-styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css" />
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="d-flex flex-column mt-5 list-group list-group-flush">
                <div class="list-group-item bg-transparent">
                    <div class="d-flex justify-content-between mb-4">
                        <h3 class="flex-item text-white">Edit Your Question</h3>
                        <a href="{{ route('questions.index') }}" class="btn btn-dark">Back to Home</a>
                    </div>
                </div>
                <div class="list-group-item rounded-1 bg-light" style="--bs-bg-opacity: 0.23">
                    <form action="{{ route('questions.update', $question) }}" method="POST" class="mt-2">
                        @csrf
                        @method("PUT")
                        <div class="form-group mb-3">
                            <label for="title" class="text-white fs-5">Title</label>
                            <input type="text" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" value="{{ old('title', $question->title) }}" placeholder="Enter Question Title" name="title" id="title"/>

                            @error('title')
                                    <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                        <div class="form-group mb-3">
                            <label for="body" class="text-white fs-5">Question</label>
                            <input type="hidden" class="form-control" value="{{ old('body', $question->body) }}" name="body" id="body"/>
                            <trix-editor input="body" placeholder="Ask Your Question" class="form-control"></trix-editor>

                            @error('body')
                                    <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="form-group mb-3 d-flex flex-column">
                            <label for="tags" class="text-white fs-5">Select Relevant Tags</label>
                            <select name="tags[]" id="tags" class="form-control select2" multiple>
                                @foreach ($tags as $tag)
                                    <option value="{{$tag->id}}" @if($question->hasThisTag($tag)) selected="selected" @endif>{{$tag->name}}</option>
                                @endforeach
                            </select>

                            @error('tags[]')
                                <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>

                        <div class="form-group mb-3">
                            <input type="submit" value="Ask Experts" class="btn btn-dark">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('page-level-scripts')
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        console.log("running");
        $('.select2').select2({
            placeholder: 'Select an option',
            maximumSelectionLength: 5,
            allowClear: true
        });

        </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js"></script>
@endsection

resources/views/questions/index.blade.php
@extends('frontend-layouts.app')

@section('page-level-styles')
    <style>
        .answers {
            padding: 2px;
            border-radius: 5px;
        }

        .answers.answered {
            border: solid 1px #4fc627;
            color: #4fc627;
        }

        .answers.has-best-answer {
            border: solid 1px #4fc627;
            background: #4fc627;
            color: white;
        }

        .answers.unanswered {
            border: solid 1px red;
            color: red;
        }
    </style>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="d-flex flex-column mt-5 list-group list-group-flush">
            <div class="list-group-item bg-transparent">
                <div class="d-flex justify-content-between mb-4">
                    <h3 class="flex-item text-white">All Questions</h3>
                    <a href="{{ route('questions.create') }}" class="btn btn-dark">Ask a Question!</a>
                </div>
            </div>
            <div id="questionList" class="list-group-item bg-transparent mt-4">
                @foreach ($questions as $question)
                    @include('questions.partials._question')
                @endforeach
            </div>
            <div class="questionListFooter list-group-item bg-transparent mt-2 mb-5">
                {{ $questions->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/questions/show.blade.php
@extends('frontend-layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="d-flex flex-column mt-5 list-group list-group-flush">
                <div id="questionTitle" class="list-group-item bg-transparent">
                    <div class="d-flex justify-content-between mb-2">
                        <h3 class="flex-item text-white fw-normal">{{ $question->title }}</h3>
                        <div>
                            <a href="{{ url("$question->url/download") }}" class="btn btn-dark text-success">Download Conversation!</a>
                            <a href="{{ route('questions.index') }}" class="btn btn-dark">Back to Home</a>
                        </div>
                    </div>
                    <div class="row text-white-50 mb-2 d-flex align-items-center">
                        @if($question->is_modified)
                            <div class="col-md-2">
                                <small>
                                    Modified: <p class="fw-light d-inline">{{ $question->modified_date }}.</p>
                                </small>
                            </div>
                        @else
                            <div class="col-md-2">
                                <small>
                                    Asked: <p class="fw-light d-inline">{{ $question->created_date }}.</p>
                                </small>
                            </div>
                        @endif
                        <div class="col-md-2">
                            <small>
                                Viewed: {{ $question->views_count }} times
                            </small>
                        </div>
                        <div class="col-md-2">
                            <small>
                                Asked By:
                                <a href="{{ route('users.profile', $question->owner) }}" class="text-white text-decoration-none fw-light ms-2">
                                    {{ $question->owner->name }}
                                </a>
                            </small>
                        </div>
                        <div class="col-6 tag-list">
                            @foreach ($question->tags as $tag)
                                <a href="" class="btn bg-primary btn-sm ms-2 fs-6 text-info text-decoration-none" style="--bs-bg-opacity:0.5;">
                                    <small>{{ $tag->name }}</small>
                                </a>
                            @endforeach
                        </div>
                    </div>
                </div>
                <div id="questionBody" class="list-group-item bg-transparent text-white">
                    <div class="row mb-5">
                        <div class="col-md-1 d-flex flex-column align-items-center">
                            @auth
                                <div id="votingPanelLoggedIn" class="mb-3">
                                    <form action="{{ route('questions.vote', [$question, 1]) }}" method="POST">
                                        @csrf
                                        <button type="submit" width="100%" title="Vote Up" class="vote-up border-0 bg-transparent {{ $question->hasMarkedUpvote(auth()->user()) ? "text-success" : "text-white" }}">
                                            <i class="fa-solid fa-caret-up fa-3x"></i>
                                        </button>
                                    </form>
                                    <h4 class="m-0 text-muted text-center">{{ $question->votes_count }}</h4>
                                    <form action="{{ route('questions.vote', [$question, -1]) }}" method="POST">
                                        @csrf
                                        <button type="submit" title="Vote Down" class="vote-down border-0 bg-transparent {{ $question->hasMarkedDownvote(auth()->user()) ? "text-danger" : "text-white" }}">
                                            <i class="fa fa-caret-down fa-3x"></i>
                                        </button>
                                    </form>
                                </div>
                            @else
                                <div id="votingPanelLoggedOut" class="mb-3">
                                    <form action="{{ route('login') }}" method="GET">
                                        @csrf
                                        <button type="submit" title="Vote Up" class="vote-up text-center border-0 bg-transparent text-white">
                                            <i class="fa fa-caret-up fa-3x"></i>
                                        </button>
                                    </form>
                                    <h4 class="m-0 text-muted text-center">{{ $question->votes_count }}</h4>
                                    <form action="{{ route('login') }}" method="GET">
                                        @csrf
                                        <button type="submit" title="Vote Down" class="vote-down text-center border-0 bg-transparent text-white">
                                            <i class="fa fa-caret-down fa-3x"></i>
                                        </button>
                                    </form>
                                </div>
                            @endauth
                            @can('markAsFavourite', $question)
                                <div id="markAsFavouritePanel" class="mb-3">
                                    @if($question->is_favourite)
                                        <form action="{{ route('questions.unfavourite', $question) }}" method="POST">
                                            @csrf
                                            @method("DELETE")
                                            <button type="submit" title="Unmark Favourite" class="favourite d-block text-center mb-2 border-0 bg-transparent">
                                                <i class="fa fa-star fa-2x text-warning"></i>
                                            </button>
                                        </form>
                                        <h4 class="text-warning text-center">{{ $question->favourites_count}}</h4>
                                    @else
                                        <form action="{{ route('questions.favourite', $question) }}" method="POST">
                                            @csrf
                                            <button type="submit" title="Mark as Favourite" class="favourite d-block text-center mb-2 border-0 bg-transparent">
                                                <i class="fa fa-star fa-2x text-white"></i>
                                            </button>
                                        </form>
                                        <h4 class="text-white text-center">{{ $question->favourites_count}}</h4>
                                    @endif
                                </div>
                            @endcan
                            <div id="editDeletePanel" class="mb-3">
                                @can('update', $question)
                                    <a href="{{ route('questions.edit', $question) }}" class="btn btn-sm btn-secondary text-warning mb-2 d-block"><strong>Edit</strong></a>
                                @endcan
                                @can('delete', $question)
                                    <form action="{{ route('questions.destroy', $question) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-secondary" style="color: red"><strong>Delete</strong></button>
                                    </form>
                                @endcan
                            </div>
                        </div>
                        <div class="col-md-11 d-flex flex-column justify-content-between">
                            <div class="questionBodyPanel">
                                {!! $question->body !!}
                            </div>
                            <div class="giveAnswerPanel">
                                <div class="text-end mt-4">
                                    <a href="{{ route('questionAnswers.create', $question) }}" class="btn btn-primary">
                                        Give an Answer!
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="answerSection bg-transparent text-white" id="list-group-item">
                    @include('answers.index');
                </div>
            </div>
        </div>
    </div>
</div>
@endsection